f = open("./PIAequipo/empleados.txt","a",encoding="utf8")
idEmpleado = int(input("Ingresa id de empleado: "))
nombre = input("Ingresa nombre del empleado: ")
direccion = input("Direccion del empleado:")
f.write(str(idEmpleado) + "|" + nombre + "|" + direccion + "\n")
f.close()
